# Generated by Django 2.2.6 on 2019-10-24 22:26

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cuisines',
            },
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('creation_date', models.DateField(default=datetime.datetime(2019, 10, 24, 22, 26, 53, 290865, tzinfo=utc))),
            ],
            options={
                'db_table': 'grocery_lists',
            },
        ),
        migrations.CreateModel(
            name='GroceryPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly')], max_length=45)),
                ('creation_date', models.DateField(default=datetime.datetime(2019, 10, 24, 22, 26, 53, 290865, tzinfo=utc))),
            ],
            options={
                'db_table': 'grocery_plans',
            },
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('height_cm', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('blood_group', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'health_profiles',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('calories', models.IntegerField()),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField(default=None)),
                ('gender', models.CharField(max_length=45)),
                ('preferred_cuisines', models.CharField(max_length=100)),
                ('diet_types', models.CharField(choices=[('VEG', 'Vegetarian'), ('NONVEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], max_length=45)),
                ('grocery_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.GroceryPlan')),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.HealthProfile')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Location')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=45)),
                ('prep_time_min', models.IntegerField()),
                ('cook_time_min', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('directions', models.TextField()),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Cuisine')),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
    ]
