# Generated by Django 2.2.6 on 2019-11-02 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cuisines',
            },
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'grocery_lists',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('calories', models.IntegerField()),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=45)),
                ('prep_time_min', models.IntegerField()),
                ('cook_time_min', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('directions', models.TextField()),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Cuisine')),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField(default=None)),
                ('gender', models.CharField(max_length=45)),
                ('preferred_cuisines', models.CharField(max_length=100)),
                ('diet_types', models.CharField(choices=[('VEG', 'Vegetarian'), ('NONVEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], max_length=45)),
                ('height_cm', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('blood_group', models.CharField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Location')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UsersAllergies',
            fields=[
                ('usersAllergies_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Allergy')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User')),
            ],
            options={
                'db_table': 'users_allergies',
            },
        ),
        migrations.CreateModel(
            name='RecipesUsers',
            fields=[
                ('recipesUsers_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('recipes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Recipe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User')),
            ],
            options={
                'db_table': 'recipes_users',
            },
        ),
        migrations.CreateModel(
            name='RecipesIngredients',
            fields=[
                ('recipesIngredients_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('ingredients_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Ingredient')),
                ('recipes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Recipe')),
            ],
            options={
                'db_table': 'recipes_ingredients',
            },
        ),
        migrations.CreateModel(
            name='GroceryPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=100)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('groceryList_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.GroceryList')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User')),
            ],
            options={
                'db_table': 'grocery_plans',
            },
        ),
        migrations.CreateModel(
            name='GroceryListIngredients',
            fields=[
                ('groceryListIngredients_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('groceryList_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.GroceryList')),
                ('ingredients_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Ingredient')),
            ],
            options={
                'db_table': 'groceryList_ingredients',
            },
        ),
    ]
