# Generated by Django 2.2.6 on 2019-11-02 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField(default=None)),
                ('gender', models.CharField(max_length=45)),
                ('preferred_cuisines', models.CharField(max_length=100)),
                ('diet_types', models.CharField(choices=[('VEG', 'Vegetarian'), ('NONVEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], max_length=45)),
                ('height_cm', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('blood_group', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfilesAllergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('allergies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Allergy')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Profile')),
            ],
            options={
                'db_table': 'profiles_allergies',
            },
        ),
        migrations.CreateModel(
            name='ProfilesRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Profile')),
            ],
            options={
                'db_table': 'recipes_profiles',
            },
        ),
        migrations.RemoveField(
            model_name='recipesusers',
            name='recipes_id',
        ),
        migrations.RemoveField(
            model_name='recipesusers',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='usersallergies',
            name='allergies_id',
        ),
        migrations.RemoveField(
            model_name='usersallergies',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='grocerylistingredients',
            name='groceryListIngredients_id',
        ),
        migrations.RemoveField(
            model_name='recipesingredients',
            name='recipesIngredients_id',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='ingredients',
            field=models.ManyToManyField(through='rest_api.GroceryListIngredients', to='rest_api.Ingredient'),
        ),
        migrations.AddField(
            model_name='grocerylistingredients',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='rest_api.RecipesIngredients', to='rest_api.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipesingredients',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GroceryPlan',
        ),
        migrations.DeleteModel(
            name='RecipesUsers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UsersAllergies',
        ),
        migrations.AddField(
            model_name='profilesrecipes',
            name='recipes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Recipe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.ManyToManyField(through='rest_api.ProfilesAllergies', to='rest_api.Allergy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recipes',
            field=models.ManyToManyField(through='rest_api.ProfilesRecipes', to='rest_api.Recipe'),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='profile_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Profile'),
            preserve_default=False,
        ),
    ]
